- title: Open Healthcare Statistics
  link: https://nhsx.github.io/open-health-statistics/
  stage: Delivery
  badge1: Open 
  badge2: Python
  badge3: Analytics
  description: Collecting statistics on open source NHS and healthcare related code repositories

- title: Digital Health Insights
  link: https://nhsx.github.io/digital-health-insights/
  stage: Complete
  badge1: GP Patient Survey 
  badge2: Digital
  badge3: Analytics
  description: What can the 2021 GP Patient Survey tell us about access to online general practice services?

- title: Open Analytics Template
  link: https://nhsx.github.io/open-analytics-template/
  stage: Complete
  badge1: Open 
  badge2: Python
  badge3: Github
  description: NHS.UK themed template for open analytics projects. Build your own open source end-to-end analytical tool using python, plotly, github.io, and github actions.

- title: eLfH-PHM-RiskStrat
  link: https://github.com/nhsx/eLfH-PHM-RiskStrat
  stage: Dissemination
  badge1: R  
  badge2: Predcition
  badge3: Analytics
  description: Risk Prediction - A practical example in R to accompany the e-LfH module.

- title: NHS App Analytics Dashboard
  link: https://github.com/nhsx/nhs-app-analytics-dashboard
  stage: Complete
  badge1: Dashboard  
  badge2: NHS App
  badge3: Analytics
  description: The NHS App dashboard enables you to see how many patients are using the NHS App across England, and which features they are using. It can be accessed by anyone with an NHS email address.

- title: Social Care Connectivity Devices
  link: https://github.com/nhsx/social-care-connectivity-devices
  stage: Complete
  badge1: Care Homes  
  badge2: IPads
  badge3: Analytics
  description: NHSX led programme to procure and gift 11,000 (data-enabled) iPads to care homes in response to COVID-19.

- title: SynPath
  link: https://github.com/nhsx/SynPath
  stage: Delivery
  badge1: Simulation
  badge2: Synthetic
  badge3: FHIR
  description: A library for generating synthetic electronic health records in FHIR v4 format using agent-based modeling to simulate patient pathways.

- title: Transform
  link: https://github.com/nhsx/transform
  stage: Dissemination
  badge1: Forecasts
  badge2: b-spline
  badge3: linear
  description: Methodology to calculate impact of aging population on activity forecasts.

