- title: Time Series Forecasting
  link: https://github.com/nhsx/Time_Series_Forecasting_MS
  stage: Delivery
  badge1: Forecasting
  badge2: Prophet
  badge3: SARIMA
  description: Base starting code for comparative forecasting developed as part of a DDaT placement 
  author: Milan Storey & Paul Carroll

- title: Privacy Fingerprint
  link: https://github.com/nhsx/PrivacyFingerprint
  stage: Delivery
  badge1: Text Data
  badge2: Privacy
  badge3: NLP
  description: Public facing materials for our commission on creating a tool to identify sensitive elements beyond PII in text
  author: Dan Schofield & Jonny Pearson

- title: ESNEFT Analysis - Diabetes Inequalities
  link: https://github.com/nhsx/p24-diabetes-inequal
  stage: Complete
  badge1: PHM Data
  badge2: Data manipulation
  badge3: OSNnx
  description: One component of our Data Science Internship project on Inequalities in Population Health Data
  author: Stephen Richer

- title: DNAttend - ML framework for predicting patient non-attendance
  link: https://github.com/nhsx/dna-risk-predict
  stage: Complete
  badge1: DNA Prediciton
  badge2: CatBoost
  badge3: PHM Data
  description: One component of our Data Science Internship project on Inequalities in Population Health Data 
  author: Stephen Richer

- title: Discrete Event Simulation - Ambulances
  link: https://github.com/nhsx/ambulance-DES
  stage: Complete
  badge1: Ambulance
  badge2: Discrete event simuation
  badge3: RSimmer
  description: Proof of concept simmer discrete event simulation for the ambulance setting - used at NHS-R 2022 Conference
  author: Martina Fonseca
  
- title: H4_12 - The role of Patient Initiated Follow-Up and Digital Outpatients in supporting the elctive recovery
  link: https://github.com/nhsx/HSMA4-12-DES-rheum
  stage: Complete
  badge1: HSMA4 Project
  badge2: discrete event simuation
  badge3: simPy
  description: Simulation of the role that PIFU and other interventions can play in addressing the elective backlog
  author: Martina Fonseca

- title: Using LIME to explain facial disease classification
  link: https://github.com/nhsx/LIME-XAI-Facial-Disease-Classification
  stage: Complete
  badge1: LIME
  badge2: XAI
  badge3: Python
  description: Application of Local Interoperable Model-agnostic Explanations to an InceptionV3 Classifyier looking at a Rosacea
  author: Anwesha Mohanty

- title: STM for survey data
  link: https://github.com/nhsx/stm-survey-text
  stage: Complete
  badge1: Free Text Analysis
  badge2: STM
  badge3: R
  description: Application of Structural Topic Modelling and visualisation of insights.  Currently private repo but being made public soon
  author: Anna Linton & Paul Carroll

- title: Txt-Ray Align
  link: https://github.com/nhsx/txt-ray-align
  stage: Complete
  badge1: Image Encoder
  badge2: Text Encoder
  badge3: Python
  description: Code to contrastively train and align text and image encoders and evaluate them on an image-to-text retrieval task using MIMIC-CXR. Currently private repo but being made public soon
  author: Dekai Zhang & Dan Schofield

- title: System Hierarchies
  link: https://github.com/nhsx/SystemHierarchies
  stage: Delivery
  badge1: Structure Mapping
  badge2: Python
  badge3: NHS
  description: Aiming to visualise and represent the structure and mapping of different NHS organisations
  author: Faaiz Shanawas

- title: Travel Times
  link: https://github.com/nhsx/nhs_time_of_travel
  stage: Delivery
  badge1: Mapping
  badge2: OSMnx
  badge3: Python
  description: PoC for an interactive mapping tool to support decision-making.
  author: Mattia Ficarelli & Paul Carroll

- title: Model Class Reliance
  link: https://github.com/nhsx/commercial-data-healthcare-predictions
  stage: Complete
  badge1: Model Explainability
  badge2: Commercial Data
  badge3: Python
  description: Internship project investigating the use of MCR to identify the value of including commerical sales data in respiratory predictions
  author: Elizabeth Dolan

- title: AIF ALlocation Streamlit Tool
  link: https://github.com/nhsx/AIF_Allocation_Tool
  stage: Complete
  badge1: Collaborative Analytics
  badge2: Streamlit
  badge3: Python
  description: Tool built to support need based allocations
  author: Craig Shenton & Christopher Todd

- title: NHS Language Corpus Discovery Tools
  link: https://github.com/nhsx/language-corpus-tools
  stage: Discovery
  badge1: Natural Language Processing
  badge2: Dataset Building
  badge3: Open
  description: Tools used as part of the NHS Language Corpus Discovery
  author: Dan Schofield

- title: Open Cyber
  link: https://nhsx.github.io/open-cyber/
  stage: Complete
  badge1: Cyber Security
  badge2: Compliance
  badge3: Open Analytics
  description: Summary statistics from the DSPT 2020/21 toolkit
  author: Martina Fonseca

- title: GP Mapping
  link: https://nhsx.github.io/gp_mapping/
  stage: Complete
  badge1: Primary Care
  badge2: Mapping
  badge3: Open Analytics
  description: This page tracks the number of patients registered at individual GP Practices
  author: Mattia Ficarelli
  
- title: The Prescribing Cost of Antibiotics
  link: https://nhsx.github.io/antibiotic_cost/
  stage: Complete
  badge1: Open Analytics
  badge2: Open Prescribing
  badge3: Python
  description: Plotly chart and folium map visualizing the prescribing cost of the antibiotics Amoxicillin, Doxycycline Hyclate and Caefalexin for Clinical Commissioning Groups (CCGs)
  author: Mattia Ficarelli

- title: Open Healthcare Statistics
  link: https://nhsx.github.io/open-health-statistics/
  stage: Complete
  badge1: Open Analytics
  badge2: GitHub
  badge3: Python
  description: Collecting statistics on open-source NHS and healthcare related code repositories
  author: Craig Shenton, Adam Ivison (NHS BSA), Arouba Zubair, Mary Amanuel

- title: Digital Health Insights
  link: https://nhsx.github.io/digital-health-insights/
  stage: Complete
  badge1: GP Patient Survey
  badge2: Digital Health
  badge3: Open Analytics
  description: What can the 2021 GP Patient Survey tell us about access to online general practice services?
  author: Mary Amanuel, Craig Shenton

- title: Open Analytics Template
  link: https://nhsx.github.io/open-analytics-template/
  stage: Complete
  badge1: Open Analytics
  badge2: GitHub
  badge3: Python
  description: NHS.UK themed template for open analytics projects. Build your own open source end-to-end analytical tool using python, plotly, github.io, and github actions.
  author: Craig Shenton 

- title: eLfH-PHM-RiskStrat
  link: https://github.com/nhsx/eLfH-PHM-RiskStrat
  stage: Complete
  badge1: R  
  badge2: Prediction
  badge3: Analytics
  description: Risk Stratification - A practical example in R to accompany the HEE e-LfH module.
  author: Matthew Francis (PHE) and Martina Fonseca

- title: NHS App Analytics Dashboard
  link: https://github.com/nhsx/nhs-app-analytics-dashboard
  stage: Complete
  badge1: Dashboard  
  badge2: NHS App
  badge3: Analytics
  description: The NHS App dashboard enables you to see how many patients are using the NHS App across England, and which features they are using. It can be accessed by anyone with an NHS email address.
  author: Arouba Zubair, Mary Amanuel

- title: Social Care Connectivity Devices
  link: https://github.com/nhsx/social-care-connectivity-devices
  stage: Complete
  badge1: Care Homes  
  badge2: IPads
  badge3: Analytics
  description: NHSX led programme to procure and gift 11,000 (data-enabled) iPads to care homes in response to COVID-19.
  author: Craig Shenton

- title: SynPath
  link: https://github.com/nhsx/SynPath
  stage: Delivery
  badge1: Simulation
  badge2: Synthetic
  badge3: FHIR
  description: A library for generating synthetic electronic health records in FHIR v4 format using agent-based modeling to simulate patient pathways.
  author: Jonny Pearson

- title: AU Data Engineering - Azure Databricks
  link: https://github.com/nhsx/au-azure-databricks
  stage: Delivery
  badge1: Data Engineering
  badge2: Azure
  badge3: ETL Pipelines
  description: Our public facing store of code used to transform our data flows using databricks compute
  author: Craig Shenton & Mattia Ficarelli

- title: AU Azure Databricks CICD
  link: https://github.com/nhsx/au-azure-databricks-cicd
  stage: Delivery
  badge1: Data Engineering
  badge2: Azure
  badge3: ETL Pipelines
  description: CICD implementation of our engineering pipelines
  author: Mattia Ficarelli & Abdu Nuhu

- title: AU Data Engineering
  link: https://github.com/nhsx/au-data-engineering
  stage: Delivery
  badge1: Data Engineering
  badge2: Azure
  badge3: ETL Pipelines
  description: Our public facing store of code used to orchestrate our data flows
  author: Craig Shenton & Mattia Ficarelli

- title: Tableau Analytics
  link: https://github.com/nhsx/au-tableau-analytics
  stage: Delivery
  badge1: Data Engineering
  badge2: Tableau
  badge3: Business Intelligence
  description: Contains Tableau workbooks for NHSX analytics projects.
  author: Ollie Jones & Mattia Ficarelli

- title: Transform
  link: https://github.com/nhsx/transform
  stage: Complete
  badge1: Forecasts
  badge2: b-spline
  badge3: linear
  description: Methodology to calculate impact of aging population on activity forecasts.
  author: Jonny Pearson

- title: NHSX Academic publications
  link: https://nhsx.github.io/nhsx-publications/
  stage: Complete
  badge1: Open Analytics
  badge2: Publications
  badge3: Python
  description: Displaying statistics on NHS and NHSX-affiliated publications on Pubmed.
  author: Martina Fonseca

- title: SynthVAE
  link: https://github.com/nhsx/SynthVAE
  stage: Delivery
  badge1: PhD Data Science Intern Scheme
  badge2: Variational AutoEnconder
  badge3: Synthetic
  description: Synthetic data generation by a Variational AutoEncoder with Differential Privacy assessed using Synthetic Data Vault metrics
  author: Jonny Pearson (on behalf of Dom Danks)

- title: SynPath - Diabetes
  link: https://github.com/nhsx/SynPath_Diabetes
  stage: Complete
  badge1: PhD Data Science Intern Scheme
  badge2: Simulation
  badge3: Synthetic
  description: SynPath module for generating type 2 diabetes pathway
  author: Jonny Pearson (on behalf of Tiyi Morris)

