- title: The Prescribing Cost of Antibiotics
  link: https://nhsx.github.io/antibiotic_cost/
  stage: Delivery
  badge1: Open Analytics
  badge2: Open Prescribing
  badge3: Python
  description: Plotly chart and folium map visualizing the prescribing cost of the antibiotics Amoxicillin, Doxycycline Hyclate and Caefalexin for Clinical Commissioning Groups (CCGs)
  author: Mattia Ficarelli

- title: Open Healthcare Statistics
  link: https://nhsx.github.io/open-health-statistics/
  stage: Complete
  badge1: Open Analytics
  badge2: GitHub
  badge3: Python
  description: Collecting statistics on open-source NHS and healthcare related code repositories
  author: Craig Shenton, Adam Ivison (NHS BSA), Arouba Zubair, Mary Amanuel

- title: Digital Health Insights
  link: https://nhsx.github.io/digital-health-insights/
  stage: Delivery
  badge1: GP Patient Survey
  badge2: Digital Health
  badge3: Open Analytics
  description: What can the 2021 GP Patient Survey tell us about access to online general practice services?
  author: Mary Amanuel, Craig Shenton

- title: Open Analytics Template
  link: https://nhsx.github.io/open-analytics-template/
  stage: Complete
  badge1: Open Analytics
  badge2: GitHub
  badge3: Python
  description: NHS.UK themed template for open analytics projects. Build your own open source end-to-end analytical tool using python, plotly, github.io, and github actions.
  author: Craig Shenton 

- title: eLfH-PHM-RiskStrat
  link: https://github.com/nhsx/eLfH-PHM-RiskStrat
  stage: Dissemination
  badge1: R  
  badge2: Prediction
  badge3: Analytics
  description: Risk Stratification - A practical example in R to accompany the HEE e-LfH module.
  author: Matthew Francis (PHE) and Martina Fonseca

- title: NHS App Analytics Dashboard
  link: https://github.com/nhsx/nhs-app-analytics-dashboard
  stage: Complete
  badge1: Dashboard  
  badge2: NHS App
  badge3: Analytics
  description: The NHS App dashboard enables you to see how many patients are using the NHS App across England, and which features they are using. It can be accessed by anyone with an NHS email address.
  author: Arouba Zubair, Mary Amanuel

- title: Social Care Connectivity Devices
  link: https://github.com/nhsx/social-care-connectivity-devices
  stage: Complete
  badge1: Care Homes  
  badge2: IPads
  badge3: Analytics
  description: NHSX led programme to procure and gift 11,000 (data-enabled) iPads to care homes in response to COVID-19.
  author: Craig Shenton

- title: SynPath
  link: https://github.com/nhsx/SynPath
  stage: Delivery
  badge1: Simulation
  badge2: Synthetic
  badge3: FHIR
  description: A library for generating synthetic electronic health records in FHIR v4 format using agent-based modeling to simulate patient pathways.
  author: Jonny Pearson

- title: Transform
  link: https://github.com/nhsx/transform
  stage: Dissemination
  badge1: Forecasts
  badge2: b-spline
  badge3: linear
  description: Methodology to calculate impact of aging population on activity forecasts.
  author: Jonny Pearson

- title: NHSX Academic publications
  link: https://nhsx.github.io/nhsx-publications/
  stage: Delivery
  badge1: Open Analytics
  badge2: Publications
  badge3: Python
  description: Displaying statistics on NHS and NHSX-affiliated publications on Pubmed.
  author: Martina Fonseca
